# 应用服务 WEB 访问端口
server:
  port: 8080

# 下面这些内容是为了让 MyBatis 映射
# 指定 Mybatis 的 Mapper 文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  # 指定 Mybatis 的实体目录
  type-aliases-package: com.wjx.usercenter.mybatis.entity

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: wjxwjx123*
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 20
      # 连接池最小空闲连接数
      minimum-idle: 5
      # 连接的最大存活时间，默认 30 分钟
      max-lifetime: 1800000
      # 连接超时时间，默认 30 秒
      connection-timeout: 30000
      # 空闲连接超时时间，默认 10 分钟
      idle-timeout: 600000